"use client";

import { useEffect, useState } from "react";
import { useAuth } from "@/context/AuthContext";
import { api } from "@/lib/api";
import { Button } from "@/components/ui/button";

type PushSubscriptionPayload = {
  endpoint: string;
  expirationTime?: number | null;
  keys: {
    p256dh: string;
    auth: string;
  };
};

function urlBase64ToUint8Array(base64String: string) {
  const padding = "=".repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding).replace(/-/g, "+").replace(/_/g, "/");
  const rawData = window.atob(base64);
  const outputArray = new Uint8Array(rawData.length);

  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i);
  }

  return outputArray;
}

export default function PushNotificationToggle() {
  const { user, token } = useAuth();
  const [supported, setSupported] = useState(false);
  const [enabled, setEnabled] = useState(false);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");

  useEffect(() => {
    let mounted = true;

    async function init() {
      if (!user || user.role !== "SHOP_OWNER" || !token) {
        if (mounted) setLoading(false);
        return;
      }

      const isSupported =
        typeof window !== "undefined" &&
        "serviceWorker" in navigator &&
        "PushManager" in window &&
        "Notification" in window;

      if (!isSupported) {
        if (mounted) {
          setSupported(false);
          setLoading(false);
        }
        return;
      }

      setSupported(true);

      try {
        const registration = await navigator.serviceWorker.register("/sw.js");
        const existing = await registration.pushManager.getSubscription();
        if (mounted) {
          setEnabled(Boolean(existing));
        }
      } catch (e) {
        if (mounted) {
          setError(e instanceof Error ? e.message : "Failed to initialize notifications");
        }
      } finally {
        if (mounted) {
          setLoading(false);
        }
      }
    }

    init();

    return () => {
      mounted = false;
    };
  }, [user, token]);

  async function enableNotifications() {
    if (!token) return;

    setError("");
    setSaving(true);

    try {
      const permission = await Notification.requestPermission();
      if (permission !== "granted") {
        throw new Error("Notification permission was not granted");
      }

      const registration = await navigator.serviceWorker.ready;
      const keyResponse = await api<{ publicKey: string }>("/api/notifications/public-key", { token });
      const publicKey = keyResponse.publicKey;

      const subscription = await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: urlBase64ToUint8Array(publicKey),
      });

      const json = subscription.toJSON();
      if (!json.endpoint || !json.keys?.p256dh || !json.keys?.auth) {
        throw new Error("Invalid push subscription generated by browser");
      }

      const payload: PushSubscriptionPayload = {
        endpoint: json.endpoint,
        expirationTime: json.expirationTime,
        keys: {
          p256dh: json.keys.p256dh,
          auth: json.keys.auth,
        },
      };

      await api("/api/notifications/subscriptions", {
        method: "POST",
        token,
        body: JSON.stringify(payload),
      });

      setEnabled(true);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to enable notifications");
    } finally {
      setSaving(false);
    }
  }

  async function disableNotifications() {
    if (!token) return;

    setError("");
    setSaving(true);

    try {
      const registration = await navigator.serviceWorker.ready;
      const existing = await registration.pushManager.getSubscription();

      if (existing) {
        await api("/api/notifications/subscriptions", {
          method: "DELETE",
          token,
          body: JSON.stringify({ endpoint: existing.endpoint }),
        });

        await existing.unsubscribe();
      }

      setEnabled(false);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to disable notifications");
    } finally {
      setSaving(false);
    }
  }

  if (!user || user.role !== "SHOP_OWNER") return null;
  if (loading) return <span className="text-xs text-gray-400">Checking notifications...</span>;
  if (!supported) {
    return <span className="text-xs text-orange-600">Push not supported on this browser</span>;
  }

  return (
    <div className="flex items-center gap-2">
      <Button
        type="button"
        variant={enabled ? "outline" : "default"}
        size="sm"
        className={enabled ? "text-green-700 border-green-300" : "bg-green-600 hover:bg-green-700"}
        onClick={enabled ? disableNotifications : enableNotifications}
        disabled={saving}
      >
        {saving ? "Saving..." : enabled ? "Notifications On" : "Enable Notifications"}
      </Button>
      {error && <span className="text-xs text-red-600 max-w-56 truncate">{error}</span>}
    </div>
  );
}
